version: 'coherence'

input_path : "./data/coherence/input/"

temporary_path: "./data/coherence/temporary/"

output_path: "./data/coherence/output/"

eliminated_topics: []

# Classification is subjective—check before running 'topic_volume_weights.py'
categories:
  Religion:
    - 10
    - 34
    - 38
  Political Economy:
    - 13
    - 35
    - 36
  Science:
    - 3
    - 41
    - 43

half_century: true

bins: true

category_plots_ymax: 2500

min_regression_year: 1600